import { HobbyItem } from '../../../types/logSessionModalTypes';

export const hobbyDetailsList: HobbyItem[] = [
  {
    name: 'Morning Sketching',
    icon: '🎨',
    streakCount: 7,
    color: '#00a2ff',
    minutesPerDay: 30,
  },
  {
    name: 'Evening Jogging',
    icon: '🏃',
    streakCount: 4,
    color: '#ff6b00',
    minutesPerDay: 25,
  },
  {
    name: 'Reading Fiction',
    icon: '📚',
    streakCount: 11,
    color: '#7b61ff',
    minutesPerDay: 40,
  },
  {
    name: 'Guitar Practice',
    icon: '🎸',
    streakCount: 6,
    color: '#00b894',
    minutesPerDay: 35,
  },
  {
    name: 'Meditation',
    icon: '🧘',
    streakCount: 9,
    color: '#f39c12',
    minutesPerDay: 20,
  },
  {
    name: 'Language Learning',
    icon: '🗣️',
    streakCount: 5,
    color: '#e84393',
    minutesPerDay: 30,
  },
  {
    name: 'Cooking New Recipes',
    icon: '🍳',
    streakCount: 3,
    color: '#e67e22',
    minutesPerDay: 45,
  },
  {
    name: 'Cycling',
    icon: '🚴',
    streakCount: 8,
    color: '#16a085',
    minutesPerDay: 50,
  },
  {
    name: 'Photography Walks',
    icon: '📷',
    streakCount: 2,
    color: '#2980b9',
    minutesPerDay: 35,
  },
  {
    name: 'Coding Challenges',
    icon: '💻',
    streakCount: 12,
    color: '#548899',
    minutesPerDay: 60,
  },
  {
    name: 'Yoga Flow',
    icon: '🧎',
    streakCount: 10,
    color: '#27ae60',
    minutesPerDay: 25,
  },
  {
    name: 'Gardening',
    icon: '🌱',
    streakCount: 6,
    color: '#6ab04c',
    minutesPerDay: 30,
  },
  {
    name: 'Chess Practice',
    icon: '♟️',
    streakCount: 14,
    color: '#9da8b4',
    minutesPerDay: 20,
  },
  {
    name: 'Journaling',
    icon: '📝',
    streakCount: 9,
    color: '#d35400',
    minutesPerDay: 15,
  },
  {
    name: 'Swimming',
    icon: '🏊',
    streakCount: 4,
    color: '#1abc9c',
    minutesPerDay: 40,
  },
  {
    name: 'Piano Practice',
    icon: '🎹',
    streakCount: 13,
    color: '#8e44ad',
    minutesPerDay: 30,
  },
  {
    name: 'Podcast Learning',
    icon: '🎧',
    streakCount: 7,
    color: '#f1c40f',
    minutesPerDay: 35,
  },
  {
    name: 'Calligraphy',
    icon: '✒️',
    streakCount: 5,
    color: '#9b59b6',
    minutesPerDay: 20,
  },
  {
    name: 'Dance Practice',
    icon: '💃',
    streakCount: 6,
    color: '#ff7675',
    minutesPerDay: 30,
  },
  {
    name: 'Bird Watching',
    icon: '🦜',
    streakCount: 3,
    color: '#2ecc71',
    minutesPerDay: 25,
  },
];
