import { PlatformPressable } from '@react-navigation/elements';
import { Ionicons } from '@expo/vector-icons';
import { Route } from '@react-navigation/routers';
import { ReactNode, useEffect } from 'react';
import Animated, {
  interpolate,
  useAnimatedStyle,
  useSharedValue,
  withSpring,
} from 'react-native-reanimated';

type IoniconName = React.ComponentProps<typeof Ionicons>['name'];

type TabBarButtonProps = {
  route: Route<string>; // Route metadata from React Navigation (key, name, params).
  isFocused: boolean;   // True when this tab is currently selected.
  color: string;        // Parent decides color based on focused/unfocused state.
  label: string | number | ReactNode;   // Label can come as plain text/number or rendered element.
  iconName: IoniconName;
  href: string;         // Web/deeplink target generated by useLinkBuilder.
  accessibilityLabel?: string;
  testID?: string;
  onPress: () => void;
  onLongPress: () => void;
};

const FOCUS_SPRING_CONFIG = { duration: 350 }; // Controls focus/unfocus animation speed.
const ICON_SCALE_RANGE = [1, 1.5] as const; // Scale icon from normal size to emphasized size.
const ICON_TOP_RANGE = [1, 9] as const; // Move icon up a little when focused.
const LABEL_OPACITY_RANGE = [1, 0] as const; // Fade label out when focused.

const TabBarButton = ({
  route,
  isFocused,
  color,
  label,
  iconName,
  href,
  accessibilityLabel,
  testID,
  onPress,
  onLongPress,
}: TabBarButtonProps) => {
  const scale = useSharedValue(0); // 0 = unfocused, 1 = focused.

  useEffect(() => {
    scale.value = withSpring(isFocused ? 1 : 0, FOCUS_SPRING_CONFIG);
  }, [scale, isFocused]); // Re-run when focus state changes.

  const animatedIconStyle = useAnimatedStyle(() => {
    const scaleValue = interpolate(scale.value, [0, 1], ICON_SCALE_RANGE);
    const top = interpolate(scale.value, [0, 1], ICON_TOP_RANGE);

    return {
      transform: [{ scale: scaleValue }],
      top,
    };
  }); // Icon grows and lifts as focus moves from 0 -> 1.

  const animatedTextStyle = useAnimatedStyle(() => {
    const opacity = interpolate(scale.value, [0, 1], LABEL_OPACITY_RANGE);
    return { opacity };
  }); // Label opacity tracks focus state.

  return (
    <PlatformPressable
      key={route.key}
      href={href}
      accessibilityState={isFocused ? { selected: true } : {}}
      accessibilityLabel={accessibilityLabel}
      testID={testID}
      onPress={onPress}
      onLongPress={onLongPress}
      className="flex-1 items-center justify-center gap-2">
      {/* Animated wrapper for the tab icon. */}
      <Animated.View style={animatedIconStyle}>
        <Ionicons name={iconName} size={24} color={color} />
      </Animated.View>
      {typeof label === 'string' || typeof label === 'number' ? (
        // Plain text/number labels render directly.
        <Animated.Text className="text-xs font-semibold" style={[{ color }, animatedTextStyle]}>{label}</Animated.Text>
      ) : label && typeof label === 'object' && '$$typeof' in label ? (
        label // If label is already a React element, keep it as-is.
      ) : label ? (
        // Safe fallback for unknown truthy values.
        <Animated.Text className="text-xs font-semibold" style={[{ color }, animatedTextStyle]}>{String(label)}</Animated.Text>
      ) : null}
    </PlatformPressable>
  );
};

export default TabBarButton;
